const PROFIL = {
  prenom:     'Antoine',
  nom:        'Dedieu',
  titre:      'PhD Candidate · AI, Data Science and Data engineering',
  institution:'University of West London - Université de Paris (ex Paris Descartes)',
  bio_courte: 'Health Data Scientist passionate about bioinformatics, AI and data science. Interdisciplinary background bridging computational biology, machine learning and health sciences.',
  bio_longue: `PhD candidate in Health Data Science at Université Paris Cité, working at the intersection of artificial intelligence, bioinformatics and public health.\n\nMy interdisciplinary background spans computational biology, machine learning, NLP and biostatistics — giving me a distinct perspective on complex health data problems.\n\nGraduate Teaching Assistant across 9 modules including Computer Architecture, Algorithms, Databases and Cyber Threat Analysis. Committed team player with strong communication and synthesis abilities.`,
  contact: {
    email:    'dedieu.anto@gmail.com',
    linkedin: 'https://www.linkedin.com/in/antoine-dedieu-09aa39198/',
    github:   '',
    twitter:  '',
    scholar:  '',
    cv:       '',
  },
  infos: [
    { label: 'Location',   value: 'London — open to relocate' },
    { label: 'Languages',  value: 'English · French' },
    { label: 'Open to',    value: 'Full-time · Part-time' },
    { label: 'Hobbies',    value: 'Artistic Gymnastics · Handball · Tennis · Music' },
  ],
  avatar_photo: 'https://media.licdn.com/dms/image/v2/D4E03AQGVV2bM5pEcTw/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1688463637238?e=1777507200&v=beta&t=dtPVzg1rcIqMZt61CgCWsukAE5NlENFzS4-VxRF16Rs',
};

const FORMATIONS = [
  { id:'f1', name:'PhD · NeuroAI', subtitle:'University of West London · 2023 – Present', details:{ Institution:'University of West London', Period:'Sept 2023 – Present', Status:'In progress', Field:'NeuroAI', Supervisor:'Prof. Konstantin Nikolic' }, tags:['NeuroAI','Spiking Neural Networks','Computational Neuroscience','Deep Learning','Python'] },
  { id:'f2', name:'Master 2 · Massive Data for Health Science', subtitle:'Université Paris Cité · 2022 – 2023', details:{ Institution:'Université Paris Cité', Period:'Sept 2022 – Jul 2023', Field:'Health Data Science / Computer Science' }, tags:['Machine Learning','Deep Learning','NLP','Survival Analysis','Biostatistics'] },
  { id:'f3', name:'Master 1 · Public Health: Massive Data', subtitle:'Université Paris Cité · 2021 – 2022', details:{ Institution:'Université Paris Cité', Period:'Sept 2021 – Aug 2022', Field:'Public Health / Massive Data' }, tags:['Epidemiology','AI in Health','Biostatistics','Data Warehouse','R'] },
  { id:'f4', name:'Licence 3 · Life Sciences: Bioinformatics', subtitle:'Université Paris Cité · 2020 – 2021', details:{ Institution:'Université Paris Cité', Period:'2020 – 2021', Field:'Computational Biology / Bioinformatics' }, tags:['Bioinformatics','Agent-Based Modelling','Python','Computational Neuroscience'] },
  { id:'f5', name:'DUT · Computer Science', subtitle:'IUT de Paris - Rives de Seine · 2018 – 2020', details:{ Institution:'IUT de Paris - Rives de Seine', Period:'2018 – 2020', Degree:'DUT Informatique' }, tags:['Algorithms','Databases','SQL','Java','C++'] },
];

const COMPETENCES = [
  { id:'c1',  name:'Machine Learning',           constellation:'core_ai',      tags:['Supervised Learning','Unsupervised Learning','Scikit-learn','Random Forest','Feature Engineering'] },
  { id:'c2',  name:'Deep Learning',              constellation:'core_ai',      tags:['Neural Networks','CNN','RNN','Transformers','PyTorch','TensorFlow'] },
  { id:'c4',  name:'Probabilistic Modeling',     constellation:'core_ai',      tags:['Bayesian Inference','MCMC','Uncertainty Quantification'] },
  { id:'c5',  name:'Reinforcement Learning',     constellation:'core_ai',      tags:['Policy Gradient','Q-Learning','Stable-Baselines3'] },
  { id:'c3',  name:'Transfer Learning',          constellation:'core_ai',      tags:['Fine-tuning','HuggingFace','Pre-trained Models','Adapters'] },
  { id:'c6',  name:'NLP',                        constellation:'specialized_ai', tags:['BERT','DistilBERT','GPT','spaCy','Medical NLP','HuggingFace'] },
  { id:'c7',  name:'Computer Vision',            constellation:'specialized_ai', tags:['Classification','Segmentation','SegFormer','OpenCV'] },
  { id:'c8',  name:'Time Series',                constellation:'specialized_ai', tags:['ARIMA','SARIMA','Anomaly Detection','Forecasting'] },
  { id:'c27', name:'Survival Analysis',          constellation:'specialized_ai', tags:['Cox Model','Kaplan-Meier','Censored Data','lifelines'] },
  { id:'c24', name:'Spiking Neural Networks',    constellation:'specialized_ai', tags:['Brian2','Neural Dynamics','Computational Neuroscience'] },
  { id:'c9',  name:'Mathematics for AI',         constellation:'maths',        tags:['Linear Algebra','Probability','Statistics','Numerical Methods'] },
  { id:'c10', name:'Statistical Inference',      constellation:'maths',        tags:['Hypothesis Testing','GLM','Bayesian Statistics','A/B Testing','Causal Inference'] },
  { id:'c11', name:'Python',                     constellation:'programming',  tags:['NumPy','Pandas','SciPy','Scikit-learn','FastAPI','Docker'] },
  { id:'c12', name:'R',                          constellation:'programming',  tags:['Shiny','ggplot2','tidyverse','Survival','R Package Dev'] },
  { id:'c13', name:'C++',                        constellation:'programming',  tags:['STL','OOP','Memory Management','Performance'] },
  { id:'c28', name:'Java',                       constellation:'programming',  tags:['OOP','Design Patterns','JVM','Software Architecture'] },
  { id:'c15', name:'PyTorch',                    constellation:'frameworks',   tags:['PyTorch Geometric','Apple MPS','ONNX','Autograd'] },
  { id:'c16', name:'Scikit-learn',               constellation:'frameworks',   tags:['XGBoost','SHAP','Optuna','Pipelines','Drift Detection'] },
  { id:'c25', name:'TensorFlow / Keras',         constellation:'frameworks',   tags:['TFLite','TF Serving','tf.data'] },
  { id:'c26', name:'MLflow',                     constellation:'frameworks',   tags:['Experiment Tracking','Model Registry','Reproducibility'] },
  { id:'c17', name:'Data Engineering',           constellation:'data_eng',     tags:['SQL','ETL/ELT','Docker','CI/CD','pytest','Model Serving'] },
  { id:'c18', name:'Data Science & Analytics',   constellation:'data_eng',     tags:['EDA','Matplotlib','Seaborn','Plotly','Experiment Design'] },
  { id:'c19', name:'Spatial Analysis & GIS',     constellation:'data_eng',     tags:['geopandas','Cartography','Spatial Stats'] },
  { id:'c14', name:'Data Visualisation',         constellation:'data_eng',     tags:['Seaborn','Plotly','ggplot2','Interactive Dashboards'] },
  { id:'c20', name:'Bioinformatics',             constellation:'bio',          tags:['OMICS','Biopython','Genomics','NGS'] },
  { id:'c29', name:'Computational Biology',      constellation:'bio',          tags:['PyMol','Agent-Based Modelling','Molecular Biology'] },
  { id:'c21', name:'Epidemiology',               constellation:'bio',          tags:['Public Health','Disease Modelling','Environmental Risk'] },
  { id:'c30', name:'Biostatistics',              constellation:'bio',          tags:['GLM','Mixed Models','Clinical Trials','Survival Models'] },
  { id:'c22', name:'Research Skills',            constellation:'research',     tags:['Literature Review','Academic Writing','Experimental Design'] },
  { id:'c23', name:'Teaching',                   constellation:'research',     tags:['Lecturing','Technical Communication','Mentoring'] },
];

const EXPERIENCES = [
  { id:'e1',  name:'PhD Researcher', subtitle:'University of West London · Oct 2023 – Present', desc:'Researching NeuroAI and developing advanced Spiking Neural Networks using insights into cognitive functions emerging from the nervous system. Under the supervision of Professor Konstantin Nikolic.', tags:['NeuroAI','Spiking Neural Networks','Research','Python','Deep Learning'] },
  { id:'e1b', name:'Graduate Teaching Assistant', subtitle:'University of West London · Oct 2023 – Present', desc:'Teaching across multiple Computer Science modules as part of the PhD programme, bridging theory and practice for undergraduate students across 9 modules including Computer Architecture, Algorithms and Databases.', tags:['Teaching','Computer Architecture','Algorithms','Databases','Java','Python'] },
  { id:'e3',  name:'Data Scientist · Computational Biologist', subtitle:'ADLIN Science · Feb–Jul 2023', desc:'Building internal R and Python packages for multi-source data management, a Shiny data cleaning application, and comprehensive tutorials for R6 object-oriented programming.', tags:['R','Python','Package Development','Shiny','Data Cleaning','Clinical Data'] },
  { id:'e2',  name:'Health Data Scientist', subtitle:'Inserm · HEGP-APHP · CARPEM · Mar–Jul 2022', desc:'Data quality analysis of the HEGP clinical data warehouse (I2B2 format): questionnaire normalisation, biological data profiling, patient profiling, R package development, and NLP GPU performance benchmarking.', tags:['R Package','Data Quality','NLP','GPU Optimisation','Data Warehouse','Health Data'] },
  { id:'e4',  name:'IT Developer Intern', subtitle:'Green Village · Apr–Jun 2020', desc:'Full-stack data engineering: database architecture, web scraping, R and Python analytics, interactive maps, server creation and automated cron tasks.', tags:['Database Architecture','Web Scraping','R','Python','Dashboard','Server'] },
];

const PROJETS = [
  { id:'p12', name:'Fashion-in-Data', type:'Computer Vision', desc:'A full CV pipeline that scrapes runway images, segments clothing with SegFormer-B2 (46 classes), extracts colour palettes in CIE Lab space via K-Means, and visualises collections in an interactive Streamlit app.', tags:['Computer Vision','SegFormer','Web Scraping','Streamlit','K-Means','HuggingFace'], github:'https://github.com/AntoineDedieu/fashion-in-data' },
  { id:'p13', name:'Time Series Anomaly Dashboard', type:'Time Series', desc:'Three anomaly detection methods applied to NYC taxi demand data, with consensus voting to reduce false positives. Every detector parameter derived from EDA findings.', tags:['Time Series','Anomaly Detection','SARIMA','Isolation Forest','Streamlit','Consensus Voting'], github:'https://github.com/AntoineDedieu/portfolio-timeseries-anomaly' },
  { id:'p14', name:'Titanic Survival Analysis', type:'Data Science', desc:'End-to-end workflow: thorough EDA motivating every feature decision, title-based age imputation, MNAR cabin encoding, and three models compared via stratified cross-validation.', tags:['scikit-learn','MLflow','Feature Engineering','EDA','Cross-validation','MNAR'], github:'https://github.com/AntoineDedieu/portfolio-titanic' },
  { id:'p15', name:'Salem Witch Trials: A Data Story', type:'Data Storytelling', desc:'A six-act data narrative exploring the 1692 Salem witch trials through quantitative analysis: timeline, geography, outcomes and social divisions. Honest data storytelling with beautiful visualisations.', tags:['Data Storytelling','EDA','Seaborn','Geographic Visualisation','geopandas','Historical Data'], github:'https://github.com/AntoineDedieu/portfolio-salem' },
  { id:'p16', name:'NLP Text Classification', type:'NLP', desc:'Fine-tuning DistilBERT on AG News (4-class) with 8,000 training samples, reaching 91% accuracy in 15 minutes on Apple MPS.', tags:['NLP','DistilBERT','HuggingFace','PyTorch','Fine-tuning','Transformers'], github:'https://github.com/AntoineDedieu/portfolio-nlp' },
  { id:'p17', name:'MLOps Platform', type:'ML Engineering', desc:'A containerised ML serving platform: FastAPI with Pydantic validation, Prometheus metrics, KS-test drift detection, 5 pytest tests, Docker Compose and GitHub Actions CI.', tags:['FastAPI','Docker','MLOps','pytest','GitHub Actions','Drift Detection'], github:'https://github.com/AntoineDedieu/portfolio-mlops' },
  { id:'p8',  name:'Interpretable Model Audit', type:'Responsible AI', desc:'A full model audit of an XGBoost credit scoring classifier — interrogating it for fairness, explainability, and deployment readiness. Two critical legal blockers surfaced.', tags:['SHAP','XGBoost','fairlearn','Explainability','Fairness','Model Audit'], github:'https://github.com/AntoineDedieu/portfolio-model-audit' },
  { id:'p9',  name:'A/B Test Simulation', type:'Experimentation', desc:'The peeking problem exposed empirically, sequential testing implemented correctly, and Bayesian posterior analysis confirming a 28% conversion lift with 100% posterior certainty.', tags:['A/B Testing','Bayesian Inference','PyMC','Sequential Testing','Statistics'], github:'https://github.com/AntoineDedieu/portfolio-ab-testing' },
  { id:'p10', name:'Graph Neural Network — Citation Data', type:'AI Research', desc:'GCN and GraphSAGE on the Cora citation network — a 23 percentage point gap over MLP baseline, proving citation structure encodes topic information.', tags:['GCN','GraphSAGE','PyTorch','PyTorch Geometric','UMAP','Deep Learning'], github:'https://github.com/AntoineDedieu/portfolio-gnn' },
  { id:'p11', name:'Causal Inference — Job Training', type:'Causal Inference', desc:'Three causal identification strategies applied to observational data: propensity score matching, IPW, and difference-in-differences, each getting closer to the true causal effect.', tags:['Causal Inference','PSM','IPW','Difference-in-Differences','Rosenbaum Bounds','Statistics'], github:'https://github.com/AntoineDedieu/portfolio-causal-inference' },
];
